---
abstract: 'Chess position with Unicode pieces'
author:
  - 'Sergey Romanov <sromanov@cpan.org>'
build_requires: {}
configure_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Games-Chess-Position-Unicode
no_index:
  directory:
    - t
    - inc
    - t
requires:
  Encode: 0
  Games::Chess: 0.003
resources:
  bugtracker: https://github.com/sergeyromanov/games-chess-position-unicode/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/sergeyromanov/games-chess-position-unicode
version: 0.01
x_test_requires:
  Test::More: 0.47
